version: "3.8"

services:
  login:
    build: 
      context: ./Login
      dockerfile: Dockerfile
    ports:
      - "6013:80"
    depends_on:
      - backend
      - postgres
    environment:
      - BACKEND_URL=http://backend:3214

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "6014:80"
    depends_on:
      - backend
      - postgres
    environment:
      - BACKEND_URL=http://backend:3214

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3214:3214"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin234
      - POSTGRES_DB=hrms_db

  postgres:
    image: postgres:14
    container_name: postgres33
    ports:
      - "5700:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin234
      - POSTGRES_DB=hrms_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:

